# Generated by Django 3.2.12 on 2024-06-08 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240607_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuser',
            name='username',
        ),
    ]
