# Generated by Django 3.2.12 on 2024-06-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_companyuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('employer', 'Employer'), ('admin', 'Admin')], default='employee', max_length=64),
            preserve_default=False,
        ),
    ]
