# Generated by Django 3.2.12 on 2024-06-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_inviteforregistration_prepared_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'WAITING FOR PERFORMER'), (2, 'IN PROGRESS'), (3, 'COMPLETED'), (4, 'CLOSED')], default=1),
        ),
    ]
